pipeline {
    options {
        ansiColor('xterm')
    }
    agent {
        kubernetes {
            yamlFile 'maven-agent.yaml'
        }
    }
    stages {
        stage('Build') {
            steps {
                container ('maven') {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
                script { withSonarQubeEnv( installationName: 'sonar-1') { // You can override the credential to be used
                        sh 'mvn clean org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar'
                        }
                }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Quality Gate Check') {
            steps {
                timeout (time: 3, unit: 'MINUTES')
                  waitForQualityGate abortPipeline: true
            }
        }
    }
}
